# classes to be used to generate icons
:brand_icons:
  :picture: icon-picture
  :video:   icon-facetime-video
  :hot:     icon-fire
  :text:    icon-file

:domain: www.dooloo.info

# these two values should be made as low as possible to allow dickheads to be
# really punished
:post_karma_barrier: -10
:comment_karma_barrier: -10

:post_sorting_cache_time: 1

# cache for 3 days
:hot_categories_cache_time: 259200

# user post karma validation window
:post_karam_tracking_time: 259200

# user comment karma validation window
:comment_karam_tracking_time: 259200

:google_analytics_id: UA-34188656-1

:google_adsense_search_id: "partner-pub-5271703842295579:8384392907"

# show random tips in banner
:tips:
  - "点击向上箭头让更多人看到这条分享，想埋了它就点击向下箭头吧！"
  - "帖子和评论支持<a href='http://github.github.com/github-flavored-markdown/'>Github Flavored Markdown</a>语法，点击格式说明了解更多"
:tips_probability: 0.2
