#configuration for jammit
#
package_assets: on # (on, off, always)
embed_assets: datauri # (on, off, datauri)
compress_assets: on # (on, off)
gzip_assets: on # (on, off)
#template_function: _.template # (defaults to the built-in micro-templating)
package_path: assets # (defaults to assets)
javascript_compressor: yui # (yui, closure)

base_url: http://dooloo.info/

#this only apply to closure
#

#compressor_options:
  #compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
  workspace:
    - public/js/lib/jquery-1.8.3.js
    - public/js/lib/*.js
    - public/js/*.js
    - app/views/js/jst/*.jst

stylesheets:
  common:
    - public/css/*.css
