defaults: &defaults
  :log_level: warn
  :search_db: 13
  :redis:
    :host: 127.0.0.1
    :port: 6379
    :db: 0

:development:
  <<: *defaults
  :log_level: debug

:test:
  :redis:
    :host: 127.0.0.1
    :port: 6379
    :db: 15

:production:
  <<: *defaults
